### ISSUE TITLE
Loved the idea - copied it

### ISSUE THREAD

**Issue by MauriceArikoglu** [Roznoshchik/Notion-no-sidebar#2]
Hi! I loved your idea, so I copied it and made it look a little "nicer" and improved the UX a bit to fit my needs!
Have a look: https://github.com/MauriceArikoglu/notion-disable-hover-toggle/tree/main

**Comment by Roznoshchik** [comment]
Hey, 

Tried it out. Looks really good. Happy this code was useful for something :D

"Little nicer” is an understatement. I’d say it looks significantly nicer :D

Cheers!
RR
