### ISSUE TITLE
Userscript failing to stop sidebar

### ISSUE THREAD

**Issue by ajtadeo** [Roznoshchik/Notion-no-sidebar#3]
Using this userscript in Tamper Monkey no longer works to stop the sidebar from appearing- probably due to some changes on Notion's end. If you're still working on this project I'm sure a lot of others would appreciate an update!

https://github.com/Roznoshchik/Notion-no-sidebar/assets/76643809/30e6403c-76b4-4a81-9eeb-9519f04d022d

**Comment by Roznoshchik** [comment]
Hi Alyssa, I just updated the code so it should work again. Here's a video of how it looks in action. 

I'm surprised that this is still an issue with notion :D 

https://share.vidyard.com/watch/Qc5tgLAkS3C2FvkuKk7ka9?

**Comment by Roznoshchik** [comment]
Let me know if you run into any trouble.
